spring:
  datasource:
    url: jdbc:mysql://localhost:3307/springplus
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

## ???? ??? ???
jwt:
  secret:
    key: ZnNhZGZzYWRmbHNhZGpmbDEyMzEyMzEyMzEyM2wya2ozbDEzajJsMzEzbDIxajNsMTJqc2Q=


logging:
  level:
    root: info                       # ✅ 전체 로그 기본 레벨 유지 (error, warn 포함)
    org.hibernate.SQL: debug         # SQL 로그
    org.hibernate.orm.jdbc.bind: trace  # 바인딩된 파라미터 출력